Ho hum, bash and make aren't similar enough.

diff --git a/branches/jjmpeg-0.10/jjmpeg-java/jni/build-ffmpeg b/branches/jjmpeg-0.10/jjmpeg-java/jni/build-ffmpeg
--- a/branches/jjmpeg-0.10/jjmpeg-java/jni/build-ffmpeg
+++ b/branches/jjmpeg-0.10/jjmpeg-java/jni/build-ffmpeg
@@ -2,7 +2,7 @@
 
 # Note that you cannot change the license options if you intend to distribute.
 
-. ./config.mk
+. ./config.sh
 
 TARGETS=${CROSS_TARGETS}
 
@@ -36,6 +36,8 @@ for TARGET in ${TARGETS_LIST[@]} ; do
 	os=${TARGETS_OS[$i]}
 	cflags="${TARGETS_CFLAGS[$i]} $DEBUG_CFLAGS"
 
+	echo "Configure for $TARGET"
+
 	$src/$FF/configure \
 	    $opts \
 	    --prefix=$this/build/$TARGET \
@@ -56,7 +58,9 @@ for TARGET in ${TARGETS_LIST[@]} ; do
 	i=`expr $i + 1`
 	make V=1 -j12 || exit 1
 	# -k is required since it fails on un-created/static .lib files
-	make V=1 -k install || (echo "Error" ; exit 1)
+	make V=1 -k install #|| (echo "Error" ; exit 1)
+	# always return ok
+	echo "Ignore installation errors"
     fi
 done
 
